name: Build and Publish Jappalyzer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to Package Registry
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_REGISTRY_URL: ${{ secrets.PACKAGE_REGISTRY_URL }}